# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import UI
import sys

class Ui_MainWindows(object):
    def setupUi(self, MainWindows):
        MainWindows.setObjectName("MainWindows")
        MainWindows.resize(590, 339)
        self.verticalLayoutWidget = QtWidgets.QWidget(MainWindows)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(430, 0, 160, 90))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Trees = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Trees.setObjectName("Trees")
        self.verticalLayout.addWidget(self.Trees)
        self.Trees_img = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Trees_img.setObjectName("Trees_img")
        self.verticalLayout.addWidget(self.Trees_img)
        self.QQ_Group = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.QQ_Group.setObjectName("QQ_Group")
        self.verticalLayout.addWidget(self.QQ_Group)
        self.QQ = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.QQ.setObjectName("QQ")
        self.verticalLayout.addWidget(self.QQ)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(MainWindows)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(430, 319, 160, 21))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.by_Trees = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.by_Trees.setObjectName("by_Trees")
        self.verticalLayout_2.addWidget(self.by_Trees)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(MainWindows)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(-1, 269, 311, 71))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Start = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Start.setFont(font)
        self.Start.setObjectName("Start")
        self.verticalLayout_3.addWidget(self.Start)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(MainWindows)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 194, 51))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Title = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.verticalLayout_4.addWidget(self.Title)
        self.talk = QtWidgets.QLabel(MainWindows)
        self.talk.setGeometry(QtCore.QRect(200, 0, 54, 12))
        self.talk.setObjectName("talk")

        self.retranslateUi(MainWindows)
        QtCore.QMetaObject.connectSlotsByName(MainWindows)

        self.Start.clicked.connect(UI.SettingW)

    def retranslateUi(self, MainWindows):
        _translate = QtCore.QCoreApplication.translate
        MainWindows.setWindowTitle(_translate("MainWindows", "刷题软件"))
        self.Trees.setText(_translate("MainWindows", "<html><head/><body><p><a href=\"https://space.bilibili.com/1069797175\"><span style=\" text-decoration: underline; color:#0000ff;\">Trees的B站页面</span></a></p></body></html>"))
        self.Trees_img.setText(_translate("MainWindows", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://space.bilibili.com/1069797175\"><span style=\" text-decoration: underline; color:#0000ff;\"></span></a><a href=\"https://space.bilibili.com/1069797175\"><img src=\":/新前缀/TREES.png\" /></a></p></body></html>"))
        self.QQ_Group.setText(_translate("MainWindows", "Q群:1231234567"))
        self.QQ.setText(_translate("MainWindows", "QQ:1401400227"))
        self.by_Trees.setText(_translate("MainWindows", "by Trees"))
        self.Start.setText(_translate("MainWindows", "开始刷题"))
        self.Title.setText(_translate("MainWindows", "刷题软件"))
        self.talk.setText(_translate("MainWindows", "text"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindows = QtWidgets.QWidget()
    ui = Ui_MainWindows()
    ui.setupUi(MainWindows)
    MainWindows.show()
    sys.exit(app.exec_())
